//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscerningEye.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ClockOffsetHours {
            get {
                return ((int)(this["ClockOffsetHours"]));
            }
            set {
                this["ClockOffsetHours"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ClockOffsetMinutes {
            get {
                return ((int)(this["ClockOffsetMinutes"]));
            }
            set {
                this["ClockOffsetMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ClockOffsetSeconds {
            get {
                return ((int)(this["ClockOffsetSeconds"]));
            }
            set {
                this["ClockOffsetSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableAlarms {
            get {
                return ((bool)(this["EnableAlarms"]));
            }
            set {
                this["EnableAlarms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableEarlyWarning {
            get {
                return ((bool)(this["EnableEarlyWarning"]));
            }
            set {
                this["EnableEarlyWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int EarlyWarningMinutes {
            get {
                return ((int)(this["EarlyWarningMinutes"]));
            }
            set {
                this["EarlyWarningMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableBallonTip {
            get {
                return ((bool)(this["EnableBallonTip"]));
            }
            set {
                this["EnableBallonTip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableNotificationTone {
            get {
                return ((bool)(this["EnableNotificationTone"]));
            }
            set {
                this["EnableNotificationTone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableTextToSpeech {
            get {
                return ((bool)(this["EnableTextToSpeech"]));
            }
            set {
                this["EnableTextToSpeech"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NotificationToneUri {
            get {
                return ((string)(this["NotificationToneUri"]));
            }
            set {
                this["NotificationToneUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{item} will be available in {time}")]
        public string EarlyWarningMessage {
            get {
                return ((string)(this["EarlyWarningMessage"]));
            }
            set {
                this["EarlyWarningMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{item} is available to be gathered in {zone}")]
        public string ItemAvailableMessage {
            get {
                return ((string)(this["ItemAvailableMessage"]));
            }
            set {
                this["ItemAvailableMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("English")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0")]
        public string UIScale {
            get {
                return ((string)(this["UIScale"]));
            }
            set {
                this["UIScale"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>1.0</string>
  <string>1.1</string>
  <string>1.2</string>
  <string>1.3</string>
  <string>1.4</string>
  <string>1.5</string>
  <string>1.6</string>
  <string>1.7</string>
  <string>1.8</string>
  <string>1.9</string>
  <string>2.0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UIScaleList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UIScaleList"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsSettingsOpen {
            get {
                return ((bool)(this["IsSettingsOpen"]));
            }
            set {
                this["IsSettingsOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Amber</string>
  <string>Blue</string>
  <string>Brown</string>
  <string>Cobalt</string>
  <string>Crimson</string>
  <string>Cyan</string>
  <string>Emerald</string>
  <string>Green</string>
  <string>Indigo</string>
  <string>Lime</string>
  <string>Magenta</string>
  <string>Mauve</string>
  <string>Olive</string>
  <string>Orange</string>
  <string>Pink</string>
  <string>Purple</string>
  <string>Red</string>
  <string>Sienna</string>
  <string>Steel</string>
  <string>Taupe</string>
  <string>Teal</string>
  <string>Violet</string>
  <string>Yellow</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UIAccentList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UIAccentList"]));
            }
            set {
                this["UIAccentList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>BaseDark</string>\r\n  <string>BaseLight</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UIAppThemeList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UIAppThemeList"]));
            }
            set {
                this["UIAppThemeList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public string UIAccent {
            get {
                return ((string)(this["UIAccent"]));
            }
            set {
                this["UIAccent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BaseLight")]
        public string UIAppTheme {
            get {
                return ((string)(this["UIAppTheme"]));
            }
            set {
                this["UIAppTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Alarm Checked</string>
  <string>Is Folklore</string>
  <string>Job</string>
  <string>Level</string>
  <string>Node Type</string>
  <string>Region</string>
  <string>Stars</string>
  <string>Start Time</string>
  <string>Zone</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection GroupingPropertyList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["GroupingPropertyList"]));
            }
            set {
                this["GroupingPropertyList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoNotDisturb {
            get {
                return ((bool)(this["DoNotDisturb"]));
            }
            set {
                this["DoNotDisturb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int NotificationToneVolume {
            get {
                return ((int)(this["NotificationToneVolume"]));
            }
            set {
                this["NotificationToneVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int TextToSpeechVolume {
            get {
                return ((int)(this["TextToSpeechVolume"]));
            }
            set {
                this["TextToSpeechVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/Dartvalince/DiscerningEye")]
        public string ReleasesUrl {
            get {
                return ((string)(this["ReleasesUrl"]));
            }
            set {
                this["ReleasesUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseInverseOnFlyout {
            get {
                return ((bool)(this["UseInverseOnFlyout"]));
            }
            set {
                this["UseInverseOnFlyout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EarlyWarningSeconds {
            get {
                return ((int)(this["EarlyWarningSeconds"]));
            }
            set {
                this["EarlyWarningSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1.2.12")]
        public string AssemblyVersion {
            get {
                return ((string)(this["AssemblyVersion"]));
            }
            set {
                this["AssemblyVersion"] = value;
            }
        }
    }
}
